apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: app.info
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              serviceName: app
              servicePort: web
