apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: web
      port: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
