apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      nodePort: {{ .Values.nodePort }}
      targetPort: {{ .Values.containerPort }}
